language: go

go:
  - "1.15.x"
  - "1.16.x"
  - "1.17.x"

jobs:
  include:
    - arch: ppc64le
      go: 1.17.x
    - arch: arm64-graviton2
      virt: vm
      os: linux
      dist: focal
      go: 1.15.x
      group: edge

install:
  - go mod tidy
  - go mod download

script:
  - go test -v ./...

after_success:
  - go test -v -short -bench . -run=^$ ./...
