name: Pre-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  develop-to-main-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout main branch
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: main

      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create PR from develop to main
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge develop into main"
          body: "This PR merges changes from develop into main."
          branch: sync-develop-to-main
          delete-branch: true
