name: Pre-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  develop-to-main-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout main branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main

      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create PR from develop to main
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge develop into main"
          body: "This PR merges changes from develop into main."
          branch: sync-develop-to-main
          delete-branch: true
