name: Pre-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  develop-to-main-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout main branch
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: main

      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create PR from develop to main
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge develop into main"
          body: "This PR merges changes from develop into main."
          branch: sync-develop-to-main
          delete-branch: true
